config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  get '/welcome/show' => "welcome#show"
  resources :medications do
    resources :reminders
  end

end

app/models/medication.rb
class Medication < ActiveRecord::Base
  belongs_to :user
  has_many :reminders , dependent: :destroy
end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
  belongs_to :medication
  # mms: unnecessary.  reminder.medication.user returns the user.  Having another reference causes issues trying to synch it all the time.  Like your MedicationsController workaround.
  belongs_to :user
  def self.default_intervals #note how this seperates out the whole thing.
    %w(morning midday afternoon evening)
  end
  #idea to just create seperate deafult intervals and use params instances to create them?
  #
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :medications, dependent: :destroy
  # mms: has_many :reminders, through: :medications # seems more appropriate and removes many of the workarounds
  has_many :reminders
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # mms: every gem in Gemfile is `require`d, unless you state otherwise in Gemfile
  # mms:  in fact, pry is only required in develop and test environment that way.
  require 'pry'

  # mms: interesting answer to this problem.  Where did you find this?  When you find solutions, I recommend to include the source, so future developers can reference it.
  before_filter :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password,:avatar) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :current_password, :avatar) }
end

end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController
  def index

    @medication = current_user.medications
  end

  def new
    @medication = Medication.new
  end

  def create
    @medication = current_user.medications.build(check_params)
    @medication.save!
    create_reminders(params[:reminders],@medication) #go through and create reminders ,@medication
      #i know this is super ugly but last minute patch/hack
      # mms: No need.  You can find a user through medication.  See Reminder class.
        @reminder = Reminder.last
        @reminder.user_id = @medication.user_id
        @reminder.save

    redirect_to medications_path
  end

  def show
    # mms: Limit to this user's medications.  Check for this in other actions too.
    @medication = current_user.medications.find(params[:id])
    @reminders = @medication.reminders.all
  end

  def edit
    @medication = Medication.find(params[:id])
    @reminders = @medication.reminders.all

  end

  def update
    @medication = Medication.find(params[:id])
    if @medication.update( check_params )
        #reset the reminders themsevles here.
        # mms: where is the flow we dicussed for reminders updates?
        redirect_to medications_path
    else
      render 'edit'
    end
  end

  def destroy
    @medication = Medication.find(params[:id])
    @medication.destroy
    redirect_to medications_path
  end


  private

  def check_params
    params.require(:medication).permit(:name,:description,:dosage)
  end

  def create_reminders(reminder_data, medication)
    reminder_data.each do |interval, should_create_reminder|
      medication.reminders.create(interval: interval) if should_create_reminder == "1" #how to prevent duplicates when update?
    end
  end


end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  def index
#nope nevermind it wont work because nested within /medications/:id
  end

  def new
    @medication = Medication.find(params[:medication_id])

  end

  def update


    if request.xhr? #alias for xml_http_request?()

      head :ok
      @reminder_u = Reminder.find(params[:id])
      @reminder_u.taken = true
      @reminder_u.save

      redirect_to root_path

    end

    @medication = Medication.find(params[:medication_id])
    create_reminders(params[:reminders],@medication) #go through and create reminders ,@medication

      @reminder = Reminder.last
      @reminder.user_id = @medication.user_id
      @reminder.save

    redirect_to edit_medication_path(@medication)
  end

  def destroy
    @medication = Medication.find(params[:medication_id])
    @reminder = Reminder.find(params[:id])
    @reminder.destroy

    redirect_to edit_medication_path(@medication) #this might not work
  end

private

def create_reminders(reminder_data, medication)
  reminder_data.each do |interval, should_create_reminder|

    medication.reminders.create(interval: interval) if should_create_reminder == "1" #how to prevent duplicates when update?
  end
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # mms:  Only authenticate the welcome route?  Seems like the reverse of the usual plan. We usually let anyone to the welcome screen, but require login for any other.
  # mms:    recommend you move this ApplicationController to lock down all routes, then open up specific routes via `skip_before_filter`
  before_action :authenticate_user!
  def index
    # mms: indentation
    # mms: look up rails "scopes" for a way to do this in the model.
    @morning_reminders = current_user.reminders.where("interval ='morning'")
     @midday_reminders = current_user.reminders.where("interval ='midday'")
     @afternoon_reminders =current_user.reminders.where("interval ='afternoon'")
     @evening_reminders = current_user.reminders.where("interval='evening'")

  end

  # mms: welcome#index AND welcome#show?  Please leave some clarifying comments.
  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Remed4me</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</head>
<body>
  <div id="custom-bootstrap-menu" class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container-fluid">
          <div class="navbar-header"><a class="navbar-brand" href="/">ReMed4Me</a>
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
              </button>
          </div>
          <div class="collapse navbar-collapse navbar-menubuilder">
              <ul class="nav navbar-nav navbar-right">


                  <li><a href="/">Reminders</a>
                  </li>
                  <li><a href="/medications">Manage Medications</a>
                  </li>
                  <li><a href="/welcome/show">About Us</a>
                  </li>
                  <% if current_user %>
                      <li><%= link_to 'Signout', destroy_user_session_path, :method => :delete %></li>
                      <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>

                  <% else %>
                      <li><%= link_to 'Signup', new_user_registration_path %></li>
                      <li><%= link_to 'Login', new_user_session_path %></li>
              <% end %>
          </div>
      </div>
  </div>
<div class = "container">
  <%= yield %>
</div>
</body>
</html>

app/views/medications/edit.html.erb
<h1>editing medication</h1>

<%= form_for @medication do |f| %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :dosage %><br>
    <%= f.number_field :dosage %>
  </p>
  <p>I'm in Section 1.</p>

  <%= f.submit %>
<% end %>

<%= link_to "delete medication",medication_path(@medication),class:"btn btn-danger", method: :delete %></p>

<h2>Reminders</h2>
<% @reminders.each do |reminder| %>
  <p><%= reminder.interval %>
    <%= link_to "Delete",[@medication,reminder], method: :delete,class:"btn-sm btn-danger" %>
</p>
<% end %>
<%= link_to "Add New Reminder",new_medication_reminder_path(@medication),class:"btn btn-primary" %>

app/views/medications/index.html.erb
<div class="page-header">
  <h1>Manage Your Medications</h1>
</div>

<% @medication.each do |medication| %>
  <p>  <span class="glyphicon glyphicon-leaf"> </span><%= link_to " #{ medication.name} (#{ medication.dosage }mg)", medication_path(medication)%>
  <%= link_to "edit", edit_medication_path(medication),class:"btn-sm btn-primary" %>
  <%= link_to "delete",medication_path(medication), method: :delete ,class:"btn-sm btn-danger"%>
</p>
<% end %>
<%= link_to "Back to Reminders!", "/",class:"btn btn-primary"%>

app/views/medications/new.html.erb
<h1>add new medication</h1>

<%= form_for @medication do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :dosage %><br>
    <%= f.number_field :dosage %>
  </p>

  <p>How often do you take this Medication?</p>
  <%= fields_for(:reminders) do |r| %>

    <% Reminder.default_intervals.each do |interval| %>
      <p><%= r.label interval, interval %>   <%= r.check_box interval %></p>
    <% end %>
  <% end %>

  <%=  f.submit %>
<% end %>

app/views/medications/show.html.erb
<h1>Show view</h1>
<p> Medication Name: <%= @medication.name %> </p>
<p><%= link_to "edit medication", edit_medication_path(@medication) %></p>

<h2>Reminders</h2>
<% @reminders.each do |reminder| %>
  <p><%= reminder.interval %>
    <%= link_to "Delete",[@medication,reminder], method: :delete,class:"btn-sm btn-danger" %>
</p>
<% end %>
<%= link_to "Add New Reminder",new_medication_reminder_path(@medication),class:"btn btn-primary" %>

app/views/reminders/index.html.erb
<h1>reminder index page ::also will be homepage of application</h1>

app/views/reminders/new.html.erb
<h1>Add new Reminder for <%= @medication.name %> </h1>

<%= form_for @medication, :url=>new_medication_reminder_path(@medication) do |f| %>
  <p>How often do you take this Medication?</p>
  <%= fields_for(:reminders) do |r| %>

    <% Reminder.default_intervals.each do |interval| %>
      <p><%= r.label interval, interval %></p>
      <p><%= r.check_box interval %></p>
    <% end %>
  <% end %>

  <%= f.submit "add new reminder" %>
<% end %>

app/views/welcome/index.html.erb
<div class="page-header">
  <h1>Reminders</h1>
</div>


 <div class="tabbable"> <!-- Only required for left/right tabs -->
   <ul class="nav nav-tabs">
     <li class="active"><a href="#tab1" data-toggle="tab">Morning</a></li>
     <li><a href="#tab2" data-toggle="tab">Midday</a></li>
     <li><a href="#tab3" data-toggle="tab">Afternoon</a></li>
     <li><a href="#tab4" data-toggle="tab">Evening</a></li>
   </ul>
   <div class="tab-content">

     <div class="tab-pane active" id="tab1"> <!-- morning -->
       <ul class="nav nav-tabs nav-stacked">
         <!-- mms: "f" is usually reserved for rails form_for vars.  Recommend "reminder" here. -->
         <!-- mms: Review this for duplication. This code is the same for morning/midday/afternoon/evening. Extract partial, pass collection. -->
        <% @morning_reminders.each do |f| %>
              <% if f.medication != nil %>
                <div class ="well well-sm">
                <li>
                  <span class="glyphicon glyphicon-leaf"> </span><%= f.medication.name %>, (<%= f.medication.dosage %>mg)
                  <% if f.taken == true %>

                      <%= button_to "Take?", medication_reminder_path(f.medication,f),method: :put,remote: true,style:"display:none;"  %>
                  <% else %>
                    <%= button_to "Take?", medication_reminder_path(f.medication,f),method: :put,remote: true ,class:"button btn-success" %>
                  <% end %>
                </li>
              </div>
              <% end %>
        <%end%>
       </ul>
     </div>

     <div class="tab-pane active" id="tab2"> <!-- midday -->
       <ul class="nav nav-tabs nav-stacked">
        <% @midday_reminders.each do |f| %>
              <% if f.medication != nil %>

              <div class ="well well-sm">
                <li>
                  <span class="glyphicon glyphicon-leaf"> </span><%= f.medication.name %>, (<%= f.medication.dosage %>mg)
                  <% if f.taken == true %>

                      <%= button_to "Take?", medication_reminder_path(f.medication,f),method: :put,remote: true,style:"display:none;"  %>
                  <% else %>
                    <%= button_to "Take?", medication_reminder_path(f.medication,f),method: :put,remote: true ,class:"button btn-success" %>
                  <% end %>
                </li>
              </div>
              <% end %>
        <%end%>
       </ul>
     </div>

     <div class="tab-pane active" id="tab3"> <!-- afternoon -->
       <ul class="nav nav-tabs nav-stacked">
        <% @afternoon_reminders.each do |f| %>
              <% if f.medication != nil %>
              <div class ="well well-sm">
                <li>
                  <span class="glyphicon glyphicon-leaf"> </span><%= f.medication.name %>, (<%= f.medication.dosage %>mg)
                  <% if f.taken == true %>

                      <%= button_to "Take?", medication_reminder_path(f.medication,f),method: :put,remote: true,style:"display:none;"  %>
                  <% else %>
                    <%= button_to "Take?", medication_reminder_path(f.medication,f),method: :put,remote: true ,class:"button btn-success" %>
                  <% end %>
                </li>
              </div>
              <% end %>
        <%end%>
       </ul>
     </div>

     <div class="tab-pane active" id="tab4"> <!-- evening -->
       <ul class="nav nav-tabs nav-stacked">
        <% @evening_reminders.each do |f| %>
        <div class ="well well-sm">
              <% if f.medication != nil %>
                <li>
                  <span class="glyphicon glyphicon-leaf"> </span><%= f.medication.name %>, (<%= f.medication.dosage %>mg)
                  <% if f.taken == true %>

                      <%= button_to "Take?", medication_reminder_path(f.medication,f),method: :put,remote: true,style:"display:none;"  %>
                  <% else %>
                    <%= button_to "Take?", medication_reminder_path(f.medication,f),method: :put,remote: true ,class:"button btn-success" %>
                  <% end %>
                </li>
              </div>
              <% end %>
        <%end%>
       </ul>
     </div>
   </div>

     <p><%= link_to "Add a New Medication + Reminder!",new_medication_path, class:"btn btn-primary" %></p>


 </div>

app/views/welcome/show.html.erb
	<div class="row show_page">
		<div class="col-md-12">
			<div class="page-header">
				<h1>
					About ReMed4Me<small>   your medication reminder app</small>
				</h1>
			</div>
      <span class="glyphicon glyphicon-plus"></span>
			<h2>
				Our Mission
			</h2>
			<p>
				No one who takes medication should feel like they're on their own. Our mission is to give people the tools, support and information they need to take their medications the way they're supposed to. ReMed4Me gives them and the people who care about them complete peace of mind.	</p>
			<p>

			</p>
      <span class="glyphicon glyphicon-check"></span>
			<h2>
				How do I use it?
			</h2>
			<p>
				It's just so easy! just sign-up/sign-in and just place in your name and email and enter the medication name and what time during the day you would like to take the medication and ReMed4Me will take care of the rest of it for you!
      </p>
			<p>

			</p>
      <span class="glyphicon glyphicon-grain"></span>
			<h2>
				Founders Story
			</h2>
			<p>
				When Eddie and Max's father accidentally took an extra dose of insulin putting him a dire situation, the brothers quickly learned how common their frightful experience was. With only 50% of patients correctly following their regimen and non-adherence causing a death every 4 minutes in the U.S. alone, they knew they had to act. The result? ReMed4Me	</p>
			<p>

			</p>
		</div>
</div>